### PR TITLE
Template architects

### PR DESCRIPTION
**Pull request by MercerT77**
Added Lead/Senior SA folders and made one minor amendment to Lead Enterprise Architect JD

### CODE REVIEW

**Review by luke-slowen — APPROVED** [review]

**Review by luke-slowen — DISMISSED** [review]
Resolved conflicts

**Review by luke-slowen — APPROVED** [review]
Structure now fine. Build is throwing an error because there is no H1 in the raw markdown files, it comes from the 'listing' template. This should be fine.

So, just the content updates to make @MercerT77 ;)

**Comment by luke-slowen** [comment]
@duncanjbrown can you just check my thinking on why the build is throwing an error pls? (because the H1 is in the listing template, not the markdown for the listing itself)

**Comment by duncanjbrown** [comment]
The H1 should no longer be in the listing template following https://github.com/DFE-Digital/dfe-job-descriptions/pull/41/files#diff-bdeb84dd08693035f8ed1e87493da9c768bfca77d22d00030fe7313f077ea200, so I think you should add it to the markdown?

**Comment by duncanjbrown** [comment]
This is interesting! we're already diverging in structure between architects and developers. Do we want to stick to the "you will/you'll have" split or just "the role" and a preamble?

Also, I think it's a good idea to remove anything that's repeated across templates like stuff about process, on the basis we can add this back mechanically later?

**Comment by duncanjbrown** [comment]
(Markdown and structure all looks good apart from those design qs)

**Comment by luke-slowen** [comment]
@MercerT77 is working on some further updates to this PR to address some of the inconsistency. Personally, not a big fan of the 'you will / you'll have' but open to discussion.

Some of the process stuff is important for architects, but will give it a think 👍

**Review by luke-slowen — APPROVED** [review]
Happy with these updates.

**Pull request merged**
